title: devlopr
subtitle: A Portfolio Jekyll Theme Built for Developers
description: >- # this means to ignore newlines until "baseurl:"
  devlopr-jekyll is a beautiful Jekyll Theme Built For Developers, which is optimized for speed and readability.

url: "" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

# Navigation
urls:
    - text: Home
      url: /
    - text: About
      url: /about
    - text: Blog
      url: /blog
    # - text: Gallery
    #   url: /gallery
    # - text: Shop
    #   url : /shop
    - text: Contact
      url : /contact
    # - text: Styleguide
    #   url: /styleguide
    # - text: Get Started
    #   url: /get-started


# Edit Author details (For multi authors check _data/authors.yml)

author_logo: cool1.png
author: 'Jake Sweany'
author_bio: Hi, I have been helping businesses improve their processes and implement automation solutions since 2008. I am a US citizen residing in Costa Rica. I am available for all kinds of contract work including web-design, automation, and writing to name a few. Let me know how I can help using the contact form.
author_email: "jakesw87@gmail.com"
author_location: Costa Rica
author_website_url: "jrootr.github.io"
typewrite-text: Glutten-free nonfat software, process, and automation solutions.

# Experiences
author_work_experiences:
            - company_name: Tunabear
              company_logo: tunabear.jpg
              company_url: https://tunabear.com
              designation: Software Engineer
              description: Data mine customer's current processes. Develop and measure KPIs. Design and implement automation solutions.
              visibility: true
            - company_name: CIMS
              company_logo: cims.png
              company_url: https://www.cims.com/
              designation: Customer Service Engineer
              description: Provided onsite support for quality management equipment in electronics manufacturing facilities.
              visibility: true
            - company_name: TTM
              company_logo: ttm.png
              company_url: https://www.ttmtech.com
              designation: Quality Engineer
              description: Analyzed and improved quality management systems in electronics manufacturing facilites.
              visibility: true
            - company_name: Coast to Coast Circuits
              company_logo: c2c.webp
              company_url: https://www.coast2coastcircuits.com/
              designation: Front End Engineer
              description: Prepared product designs for manufacturing. Provided feedback to customers to improve manufacturability.
              visibility: true

# Skill Levels
author_skill_levels:
              - description: Python
                percentage: 80%
                visibility: true 
              - description: Javascript
                percentage: 85%
                visibility: true 
              - description: React Framework Library
                percentage: 35%
                visibility: true 
              - description: Perl
                percentage: 40%
                visibility: true 
              - description: Java
                percentage: 55%
                visibility: true 
              - description: SQL
                percentage: 70%
                visibility: true 
              - description: HTML/CSS
                percentage: 75%
                visibility: true 
              - description: Dart/Flutter
                percentage: 40%
                visibility: true 
              - description: Unix/CShell
                percentage: 90%
                visibility: true 
              - description: C/C++
                percentage: 65%
                visibility: true 
              - description: C#/VB
                percentage: 85%
                visibility: true 
              - description: English
                percentage: 99%
                visibility: true 
              - description: Spanish
                percentage: 70%
                visibility: true 


# Education
author_education_details:
              - college_logo: traversy_media.png
                college_name: Traversy Media
                college_url: https://www.traversymedia.com/
                description: Modern JS From The Beginning
                visibility: true
              - college_logo: job_ready.png
                college_name: Job Ready Programmer
                college_url: https://www.jobreadyprogrammer.com/
                description:  The Complete Oracle SQL Certification Course 
                visibility: true
              - college_logo: msi.png
                college_name: Management and Strategy Institute
                college_url: https://www.msicertified.com/
                description: Six Sigma Champion Certified
                visibility: true
              - college_logo: msi.png
                college_name: Management and Strategy Institute
                college_url: https://www.msicertified.com/
                description: Six Sigma Lean Blackbelt Professional
                visibility: true
              - college_logo: adda.jpg
                college_name: American Design and Drafting Association
                college_url: https://www.adda.org/
                description: Certified Drafter
                visibility: true
              - college_logo: tec-ease.png
                college_name: TEC-EASE INC.
                college_url: https://www.tec-ease.com/
                description: Geometric Dimensioning and Tolerancing Training
                visibility: true
              - college_logo: logo-suny_transparent.png
                college_name: State University of New York
                college_url: https://www.suny.edu
                description: Electrical Engineering
                visibility: true


# Projects
author_project_details:
              - project_thumbnail: gamershub.png
                project_title: Gamers Hub
                project_description: A Platform built for Gamers and Game Devs
                project_url: https://gamershub.in
                visibility: false
              - project_thumbnail: hack4r.PNG
                project_title: Hack4r
                project_description: A Platform built for Hackers and Penetration Testers
                project_url: https://hack4r.com
                visibility: false

# social links
twitter_username: 
github_username:  
facebook_username: 
linkedin_username: 
behance_username: 
instagram_username: 
medium_username: 
telegram_username: 
dribbble_username: 
flickr_username: 

#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

# disqus_shortname: sujay-kundu
hyvor_talk_website_id: 

# wakatime username (coding activity)
wakatime_username: 

# mailchimp embedded form url (newsletter):
mailchimp_form_url: 

# contact form - (choose formspress or getform)
# getform_endpoint: 83b703c3-9e47-4df4-ac55-e24d7eb02abc
formspree_email: 

# releases - widget can be (sidebar, modal or embed)
olvy_organization: devlopr
olvy_widget_type: sidebar

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: false
show_author_project_details: true
show_author_skill_levels: true

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

collections:
  products:
    output: true
  authors:
    output: true

defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext
  -
    scope:
      path: ""
      type: authors
    values:
      layout: author
      permalink: /blog/authors/:slug
  -
    scope:
      path: 'assets/**'
    values:
      sitemap: false

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-admin

# Jekyll Admin Config
jekyll_admin:
  # hidden_links:
  #   - posts
  #   - pages
  #   - staticfiles
  #   - datafiles
  #   - configuration
  homepage: "posts"


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.

### Switching Deployment Strategy (in DEPLOY_STRATEGY) file change the key accordingly:
# none - For no default
# gh-pages - For Github Pages
# firebase - For Firebase Hosting

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - assets/bower_components/isotope-layout/README.md
  - assets/bower_components/icono/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-svg-core/README.md
  - assets/bower_components/ghosthunter/README.md
  - assets/bower_components/nanobar/README.md
  - assets/bower_components/lightgallery/demo/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/free-brands-svg-icons/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/free-solid-svg-icons/README.md
  - assets/bower_components/jquery-mousewheel/README.md
  - assets/bower_components/get-size/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome/README.md
  - assets/bower_components/jquery-mousewheel/ChangeLog/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-regular/README.md
  - assets/bower_components/desandro-matches-selector/README.md
  - assets/bower_components/ev-emitter/README.md
  - assets/bower_components/font-awesome/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-solid/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-webfonts/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-brands/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-common-types/README.md
  - assets/bower_components/ghosthunter/example/Index.html
  - assets/bower_components/lightgallery/test/lightgallery.html
  - assets/bower_components/masonry-layout/README.md
  - assets/bower_components/imagesloaded/README.md


destination: ./build
